blunderbuss:
  request_count: 0 # Assign 0 people to PRs
  max_request_count: 1 # At least minimize number of assignments
approve:
- commandHelpLink: ""
  repos:
  - openshift/osd-example-operator
  require_self_approval: false
lgtm:
- repos:
  - openshift/osd-example-operator
  review_acts_as_lgtm: true
